version: '3'

services:
  db:
    image: postgres:9
    restart: unless-stopped
    container_name: passwordSafeDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: passwordSafe
    ports:
      - "5430:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

